"""added relationship to documents table

Revision ID: 0dd49a93fa4c
Revises: ae2b0caae48c
Create Date: 2021-09-12 22:59:00.878993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd49a93fa4c'
down_revision = 'ae2b0caae48c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
