"""empty message

Revision ID: 1f3535cafa27
Revises: 0dd49a93fa4c
Create Date: 2021-09-12 23:00:07.259547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3535cafa27'
down_revision = '0dd49a93fa4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
