"""added relationship to documents table

Revision ID: 358d5d26944c
Revises: c4836dd7b9ee
Create Date: 2021-09-12 22:53:03.615599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358d5d26944c'
down_revision = 'c4836dd7b9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
