"""empty message

Revision ID: ae2b0caae48c
Revises: 358d5d26944c
Create Date: 2021-09-12 22:55:53.180541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2b0caae48c'
down_revision = '358d5d26944c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
