version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    command: >
      bash -c "alembic upgrade head
      && python populate.py
      && uvicorn main:app --host 0.0.0.0 --port 8080"
    environment:
      POSTGRES_HOST: db
      ES_INDEX: documents
      ES_HOST: es
      WAIT_HOSTS: pg_db:5432, es:9200
    ports:
      - 8080:8080
    depends_on:
      - pg_db
      - es

  pg_db:
    image: postgres:13.4
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: julia
      POSTGRES_PASSWORD: root
      POSTGRES_DB: documents
    ports:
      - 5432:5432

  es:
    image: elasticsearch:7.14.1
    container_name: es
    restart: always
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
