
version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    depends_on:
      - pg_db

  pg_db:
    image: postgres:13.4
    container_name: db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: julia
      POSTGRES_PASSWORD: root
      POSTGRES_DB: documents
